/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickinvaders;

import java.awt.Event;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mc668903
 */
public class SaisiNom extends javax.swing.JFrame implements Runnable{

    private Menu m;
    
    // attribut permettant de savoir la saisie du jeu
    private boolean nomSaisi = false;
    
    // attribut permettant d'enregistrer le score du joueur
    private int scoreSaisi;
    
    // getter pour récupérer l'attribut saisieNom
    public boolean getNomSaisi(){
        return this.nomSaisi;
    }
    
    // setter permettant de configurer l'attribut nomSaisi
    public void setNomSaisi(boolean saisi){
        this.nomSaisi = saisi;
    }
    
    // setter permettant de configurer l'attribut scoreSaisi
    public void setScoreSaisi(int sc){
        this.scoreSaisi = sc;
    }
    
    /**
     * Creates new form SaisiNom
     */
    public SaisiNom() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 104));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 37, 280, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 68, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saisissez votre nom :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 380, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setNomSaisi(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisiNom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisiNom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisiNom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisiNom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaisiNom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        this.setVisible(true);
        this.setTitle("Vous avez obtenu le meilleur score !");
        while(this.nomSaisi == false){
            Event event = null;
            this.action(event, jButton1);
            /** On fait attendre le thread car à priori il fonctionne trop vite
            * peut être dû aux faits que l'on fait pas assez de chose dans le thread
            * Explication de Mr Simonet
            **/
            try {
                Thread.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(SaisiNom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // enregistrement du nom rentré
        try{
            FileOutputStream file = new FileOutputStream("HighScoresNom.dat");
            ObjectOutputStream os = new ObjectOutputStream(file);

            os.writeChars(this.jTextField1.getText());           
            os.flush();
            os.close();            
        }            
        catch(FileNotFoundException err){
            System.err.println("fichier inconnu");
        } catch (IOException ex) {
            Logger.getLogger(SaisiNom.class.getName()).log(Level.SEVERE, null, ex);
        }
        // enregistrement du score
        try{
            FileOutputStream file = new FileOutputStream("HighScoresScore.dat");
            ObjectOutputStream os = new ObjectOutputStream(file);

            os.writeInt(scoreSaisi);
            os.flush();
            os.close();            
        }            
        catch(FileNotFoundException err){
            System.err.println("fichier inconnu");
        } catch (IOException ex) {
            Logger.getLogger(SaisiNom.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }
}
